version: "3"
services:
  proxy:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - shedule-server
      - shedule-client

  db:
    image: mariadb:10.3.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shedule
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - '3306'
    ports:
      - '3306:3306'



  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/swagger.yml:/usr/share/nginx/html/sample.yaml
    environment:
      API_URL: sample.yaml
    ports:
      - "4000:8080"